name: .NET MVC CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./Mini-Warehous-Manager-System/Mini-warehous-manager-system.csproj
      
    - name: Build Project
      run: dotnet build ./Mini-Warehous-Manager-System/Mini-warehous-manager-system.csproj --no-restore --configuration Release